name: Ejecucion con Envios de Correo

on:
  schedule:
    - cron: '20 09 * * *' # Tu hora programada
  workflow_dispatch: # Para que puedas darle al botón de "Run" manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          python -m spacy download es_core_news_sm

      - name: Correr Script y Enviar Correo
        env:
          # Sin estas dos líneas, el archivo .py falla
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python analisis.py

      - name: Subir Resultados (Opcional)
        uses: actions/upload-artifact@v4
        with:
          name: Reporte-Final
          path: |
            reporte_final_sentimientos.png
            analisis_resultados_completo.xlsx
