name: Ejecucion Analisis Drive

on:
  schedule:
    - cron: '0 12 * * *' # Se ejecuta a las 12 PM UTC todos los días
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          python -m spacy download es_core_news_sm

      - name: Correr Analisis
        run: python analisis.py

      - name: Subir Resultados
        uses: actions/upload-artifact@v3
        with:
          name: Reporte-IA
          path: |
            reporte_final_sentimientos.png
            analisis_resultados_completo.xlsx
